name: hypertrip
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  nb_utils: ^5.0.8
  dio: ^5.2.1+1
  cached_network_image: ^3.2.3
  loading_animation_widget: ^1.2.0+4
  get_it: ^7.6.0
  flutter_bloc: ^8.1.3
  bloc: ^8.1.2
  formz: ^0.6.0
  equatable: ^2.0.5
  logger: ^1.4.0
  page_transition: ^2.0.9
  progress_dialog_null_safe: ^1.0.7
  geolocator: ^9.0.2
  flutter_svg: ^2.0.5
  timeline_tile: ^2.0.0
  collection: ^1.17.0
  readmore: ^2.2.0
  flutter_native_splash: ^2.2.19
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.2
  build_runner: ^2.3.3
  freezed: ^2.3.5
  json_serializable: ^6.6.2

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/logo.png

flutter:

  uses-material-design: true
  assets:
    - assets/images/icons/
    - assets/images/
    - assets/

  fonts:
    - family: Nunito
      fonts:
        - asset: fonts/Nunito-Light.ttf
          weight: 300
        - asset: fonts/Nunito-Regular.ttf
          weight: 400
        - asset: fonts/Nunito-Medium.ttf
          weight: 500
        - asset: fonts/Nunito-SemiBold.ttf
          weight: 600
        - asset: fonts/Nunito-Bold.ttf
          weight: 700
    - family: OpenSans
      fonts:
        - asset: fonts/OpenSans-Light.ttf
          weight: 300
        - asset: fonts/OpenSans-Regular.ttf
          weight: 400
        - asset: fonts/OpenSans-Medium.ttf
          weight: 500
        - asset: fonts/OpenSans-SemiBold.ttf
          weight: 600
        - asset: fonts/OpenSans-Bold.ttf
          weight: 700
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Light.ttf
          weight: 300
        - asset: fonts/Roboto-Regular.ttf
          weight: 400
        - asset: fonts/Roboto-Medium.ttf
          weight: 500
        - asset: fonts/Roboto-Bold.ttf
          weight: 700

